#!/data/data/com.termux/files/usr/bin/bash
#########用于删除容器#########
printf "\033[38;5;123m"
cd /data/data/com.termux/files/usr/etc/container.conf.d
for i in {1..100};do
  if [[ -e container-${i}.conf ]];then
    export $(cat container-${i}.conf)
    echo -e "[$i] $NAME"
  fi
done
read -p "SELECT A CONTAINER TO DELEATE: " CONTAINER
echo -e "[WARNING!!!] ALL YOUR FILES IN THIS CONTAINER WILL BE DELEATED"
echo -e "PRESS ENTER TO CONTINUE OR PRESS CTRL-C TO EXIT"
read
export $(cat /data/data/com.termux/files/usr/etc/container.conf) >> /dev/null
export $(cat /data/data/com.termux/files/usr/etc/container.conf.d/container-${CONTAINER}.conf) >> /dev/null
#删除旧容器
clear
echo -e "UNMOUNTING"
echo -e "[START] UNMOUNT /dev"
umount -lvf ${CHROOT_DIR}/dev >/dev/null 2>&1 #解除/dev的挂载
echo -e "[DONE ] UNMOUNT /dev"
echo -e "[START] UNMOUNT /sys"
umount -lvf ${CHROOT_DIR}/sys >/dev/null 2>&1 #解除/sys的挂载
echo -e "[DONE ] UNMOUNT /sys"
echo -e "[START] UNMOUNT /proc" 
umount -lvf ${CHROOT_DIR}/proc >/dev/null 2>&1 #解除/proc挂载
echo -e "[DONE ] UNMOUNT /proc"
echo -e "[START] UNMOUNT /sdcard" 
umount ${CHROOT_DIR}/sdcard >/dev/null 2>&1 #解除/sdcard的挂载
echo -e "[DONE ] UNMOUNT /sdcard"
echo -e "[START] UNMOUNT ${CHROOT_DIR}" 
umount -lvf ${CHROOT_DIR} >/dev/null 2>&1 #解除目录自身挂载
losetup -d ${CHROOT_IMG} >/dev/null 2>&1 #解除img镜像与虚拟设备的关联
echo -e "[DONE ] UNMOUNT ${CHROOT_DIR}"
echo -e "REMOVING CONTAINER"
sleep 2s
if [[ ${CHROOT_DIR} != "" ]];then
  rm -rfv ${CHROOT_DIR}
fi
if [[ ${CHROOT_IMG} != "" ]];then
  rm -rfv ${CHROOT_IMG}
fi
rm /data/data/com.termux/files/usr/etc/container.conf.d/container-${CONTAINER}.conf
rm /data/data/com.termux/files/usr/etc/container.conf
#选择新容器
unset CONTAINER
if [[ $( ls /data/data/com.termux/files/usr/etc/container.conf.d ) != "" ]];then
  cd /data/data/com.termux/files/usr/etc/container.conf.d
  for i in {1..100};do
    if [[ -e container-${i}.conf ]];then
      export $(cat container-${i}.conf)
      echo -e "\033[38;5;123m[$i] $NAME"
    fi
  done
  read -p "SELECT A NEW CONTAINER: " CONTAINER
  echo CONTAINER=${CONTAINER} >> /data/data/com.termux/files/usr/etc/container.conf
fi
printf "\033[0m"
