#!/data/data/com.termux/files/usr/bin/bash
#########用于容器安装#########
clear
echo -e ""
echo -e "\033[38;5;123m//"
echo -e ""
i1=$(($(stty size|awk '{print $2}')))
let i1=$(($i1))
i1=$(($i1-9))
echo -e "\033[46;37mCONTAINER_CREAT$(yes " "|sed $i1'q'|tr -d '\n')\033[0m"
echo -e ""
echo -e "\033[38;5;123m//"
echo -e ""
sleep 0.1s
if [[ ! -e /data/data/com.termux/files/usr/etc/container.conf.d ]];then
  mkdir -p /data/data/com.termux/files/usr/etc/container.conf.d
fi
printf  "\033[38;5;123m"
read -p "ENTER THE NAME OF THIS CONTAINER: " NAME
read -p "ENTER THE ABSOLUTE PATH OF THIS CONTAINER: " CHROOT_DIR
read -p "DO YOU WANT TO INSTALL THIS CONTAINER IN AN IMAGE FILE [y/n]?" USE_IMAGE
if [[ ${USE_IMAGE} = "y" ]];then
  read -p "ENTER THE ABSOLUTE PATH OF IMAGE FILE: " CHROOT_IMG_PATH
  read -p "ENTER THE NAME OF IMAGE FILE: " CHROOT_IMG_NAME
  read -p "ENTER THE SIZE OF IMAGE FILE(UNIT IS GB): " SIZE
fi
read -p "ENTER THE ROOTFS DOWNLOAD LINK: " URL
echo -e "DOWNLOADING ROOTFS"
sleep 1s
rm -rf /data/data/com.termux/files/usr/tmp/container >/dev/null 2>&1
mkdir -p /data/data/com.termux/files/usr/tmp/container >/dev/null 2>&1
cd /data/data/com.termux/files/usr/tmp/container >/dev/null 2>&1
#下载rootfs
wget ${URL}
sudo mkdir -p ${CHROOT_DIR}
if [[ ! ${CHROOT_IMG_NAME} = "" ]];then  #创建img镜像并挂载
  echo -e "CREATING IMAGE FILE"
  sudo mkdir -p ${CHROOT_IMG_PATH}
  cd ${CHROOT_IMG_PATH}
  sudo dd if=/dev/zero of=${CHROOT_IMG_NAME}.img bs=1G count=${SIZE}
  sudo mkfs.ext4 ${CHROOT_IMG_NAME}.img
  echo -e "MOUNTING IMAGE FILE"
  sleep 1s
  LOOP=$(sudo losetup -f)
  sudo losetup  ${LOOP} ${CHROOT_IMG_NAME}.img  >/dev/null 2>&1
  sudo mount ${LOOP} ${CHROOT_DIR}  >/dev/null 2>&1
fi
echo -e "EXTRACTING ROOTFS"
sleep 2s
#解压rootfs
ROOTFS=$(ls /data/data/com.termux/files/usr/tmp/container/)
case $ROOTFS in
  *tar.gz|*tgz|*tar) tar -xzvf /data/data/com.termux/files/usr/tmp/container/$ROOTFS -C ${CHROOT_DIR};;
  *tar.xz|*txz) tar -xvf /data/data/com.termux/files/usr/tmp/container/$ROOTFS -C ${CHROOT_DIR};;
  *) echo 'UNKNOW FILE FORMAT';exit 0;;
esac
echo -e ""
echo -e "\033[38;5;123mWRITING CONFIGURE FILE"
sleep 1s
#写入配置
#遍历获取未使用的配置文件
for i1 in {1..100};do
  if [[ ! -e /data/data/com.termux/files/usr/etc/container.conf.d/container-${i1}.conf ]];then
    CONTAINER=$i1
    break
  fi
done
echo NAME=${NAME} >> /data/data/com.termux/files/usr/etc/container.conf.d/container-${CONTAINER}.conf
echo CHROOT_DIR=${CHROOT_DIR} >> /data/data/com.termux/files/usr/etc/container.conf.d/container-${CONTAINER}.conf
if [[ ${CHROOT_IMG_NAME} != "" ]];then
  echo CHROOT_IMG=${CHROOT_IMG_PATH}/${CHROOT_IMG_NAME}.img >> /data/data/com.termux/files/usr/etc/container.conf.d/container-${CONTAINER}.conf
else
  echo CHROOT_IMG= >> /data/data/com.termux/files/usr/etc/container.conf.d/container-${CONTAINER}.conf
fi
export NEW_CONTAINER=${CONTAINER}
export $(cat /data/data/com.termux/files/usr/etc/container.conf) >> /dev/null
export CONTAINER_BK=${CONTAINER}
unset CONTAINER
sed -i "s/CONTAINER=$CONTAINER_BK/CONTAINER=$NEW_CONTAINER/" /data/data/com.termux/files/usr/etc/container.conf
echo -e "REMOVING DOWNLOADED ROOTFS\033[0m"
sleep 1s
#清空tmp
rm -rf /data/data/com.termux/files/usr/tmp/container
#   │  │   ╔══╝╔══║╔══╝
# ── ── ── ║   ║  ║║
#   │  │   ╔══╝║  ║╔══╝
# ── ── ── ║   ║  ║║
#   │  │   ═══╝═══╝╝

