#!/data/data/com.termux/files/usr/bin/bash
#########用于容器帮助信息#########
echo -e "              \033[32m┌───────────┐"
echo -e "              │ ┌───────┐ │"
echo -e "              │ │  \033[33m┌───────────┐"
echo -e "              \033[32m│ │  \033[33m│ ┌───────┐ │"
echo -e "              \033[32m│ │  \033[33m│ │  \033[32m│ │  \033[33m│ │"
echo -e "              \033[32m│ └──\033[33m│ │\033[32m──┘ │  \033[33m│ │"
echo -e "              \033[32m└────\033[33m│ │\033[32m────┘  \033[33m│ │"
echo -e "                   \033[33m│ └───────┘ │"
echo -e "                   \033[33m└───────────┘"
echo -e "\033[34m═╔╝╔═╝╔═║╔╔ ║ ║║ ║  ╔═╝╔═║╔═ ═╔╝╔═║╝╔═ ╔═╝╔═║"
echo -e " ║ ╔═╝╔╔╝║║║║ ║ ╝ ═╝║  ║ ║║ ║ ║ ╔═║║║ ║╔═╝╔╔╝"
echo -e " ╝ ══╝╝ ╝╝╝╝══╝╝ ╝  ══╝══╝╝ ╝ ╝ ╝ ╝╝╝ ╝══╝╝ ╝"
echo -e "\033[38;5;123mUsage:"
echo -e " container                   #Run container"
echo -e " container -c                #Creat a new container"
echo -e " container -S                #Select a container"
echo -e " container -s                #Settings"
echo -e " container -r                #Remove a container"
echo -e " container -m                #Mount image file"
echo -e " container -un               #Unmount container"
echo -e " container -bk               #Backup container"
echo -e " container -R [backup file]  #Restore container"
echo -e " container -up               #Update this script"
echo -e " container -h                #Show helps\033[0m"
#   │  │   ╔══╝╔══║╔══╝
# ── ── ── ║   ║  ║║
#   │  │   ╔══╝║  ║╔══╝
# ── ── ── ║   ║  ║║
#   │  │   ═══╝═══╝╝

