#!/data/data/com.termux/files/usr/bin/bash
#########用于容器选择#########
clear
echo -e ""
echo -e "\033[38;5;123m//"
echo -e ""
i1=$(($(stty size|awk '{print $2}')))
let i1=$(($i1))
i1=$(($i1-16))
echo -e "\033[46;37mCONTAINER_SELECT$(yes " "|sed $i1'q'|tr -d '\n')\033[0m"
echo -e ""
echo -e "\033[38;5;123m//"
echo -e ""
sleep 0.1s
cd /data/data/com.termux/files/usr/etc/container.conf.d
for i in {1..100};do
  if [[ -e container-${i}.conf ]];then
    export $(cat container-${i}.conf)
    echo -e "\033[38;5;123m[$i] $NAME"
  fi
done
export $(cat /data/data/com.termux/files/usr/etc/container.conf) >> /dev/null
export CONTAINER_BK=${CONTAINER}
unset CONTAINER
read -p "SELECT A CONTAINER: " CONTAINER
sed -i "s/CONTAINER=$CONTAINER_BK/CONTAINER=$CONTAINER/" /data/data/com.termux/files/usr/etc/container.conf
#   │  │   ╔══╝╔══║╔══╝
# ── ── ── ║   ║  ║║
#   │  │   ╔══╝║  ║╔══╝
# ── ── ── ║   ║  ║║
#   │  │   ═══╝═══╝╝
