#!/data/data/com.termux/files/usr/bin/bash
#########用于没用的开头输出#########
clear
UNMOUNT(){
  sleep 0.1s
  echo -e ""
  echo -e "\033[\033[38;5;123m//\033[0m"
  echo -e ""
  sleep 0.1s
  echo -e "\033[46;37mUNMOUNTING                                                            \033[0m"
  sleep 0.1s
  echo -e ""
  echo -e "\033[\033[38;5;123m//\033[0m"
  echo -e ""
  sleep 0.1s
}
CONFIGURE(){
sleep 0.1s
  echo -e ""
  echo -e "\033[\033[38;5;123m//\033[0m"
  echo -e ""
  sleep 0.1s
  echo -e "\033[46;37mCONFIGURE                                                             \033[0m"
  sleep 0.1s
  echo -e ""
  echo -e "\033[\033[38;5;123m//\033[0m"
  echo -e ""
  sleep 0.1s
}
UPDATE(){
sleep 0.1s
  echo -e ""
  echo -e "\033[\033[38;5;123m//\033[0m"
  echo -e ""
  sleep 0.1s
  echo -e "\033[46;37mUPDATING                                                              \033[0m"
  sleep 0.1s
  echo -e ""
  echo -e "\033[\033[38;5;123m//\033[0m"
  echo -e ""
  sleep 0.1s
}
MOUNT(){
sleep 0.1s
  echo -e ""
  echo -e "\033[\033[38;5;123m//\033[0m"
  echo -e ""
  sleep 0.1s
  echo -e "\033[46;37mMOUNTING                                                              \033[0m"
  sleep 0.1s
  echo -e ""
  echo -e "\033[\033[38;5;123m//\033[0m"
  echo -e ""
  sleep 0.1s
}
CONTAINER(){
  echo -e "\033[\033[38;5;123mLOADING"
  i2=0
  for i1 in {117,123,116,159,158,122} {122,158,159,116,123,117} {117,123,116,159,158,122} {122,158,159,116,123,117} {117,123,116,159,158,122} {122,158,159,116,123,117} {117,123,116,159,158,122} {122,158,159,116,123,117} {117,123,116,159,158,122} {122,158,159,116,123,117} {117,123,116,159,158,122} {122,158,159};do
    i2=$(($i2+1))
    echo -e "\033[2H\033[${i2}G\033[38;5;${i1}m/"
  sleep 0.03s
  done
  echo -e "\033[\033[38;5;123mTERMUX-CONTAINER\033[0m"
  sleep 0.1s
  echo -e "\033[\033[38;5;123mGPL-V3 LICENSE\033[0m"
  sleep 0.1s
  echo -e "\033[\033[38;5;123mNO WARRANTY\033[0m"
  sleep 0.1s
  echo -e ""
  echo -e "\033[\033[38;5;123m//\033[0m"
  echo -e ""
  sleep 0.1s
  echo -e "\033[38;5;123m<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\033[0m"
  echo -e "\033[38;5;123m               ╔═╝  ╔═║  ╔═   ═╔╝  ╔═║  ╝  ╔═   ╔═╝  ╔═║              \033[0m"
  echo -e "\033[38;5;123m               ║    ║ ║  ║ ║   ║   ╔═║  ║  ║ ║  ╔═╝  ╔╔╝              \033[0m"
  echo -e "\033[38;5;123m               ══╝  ══╝  ╝ ╝   ╝   ╝ ╝  ╝  ╝ ╝  ══╝  ╝ ╝              \033[0m"
  echo -e "\033[38;5;123m>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\033[0m"
  echo -e ""
  sleep 0.1s
  echo -e "\033[\033[38;5;123m//\033[0m"
  echo -e ""
  sleep 0.1s
  echo -e "\033[\033[38;5;123mKERNEL $(uname --kernel-release)\033[0m"
  sleep 0.1s
  echo -e "\033[\033[38;5;123mTIME $(date|awk '{print $4}')\033[0m"
  sleep 0.1s
  echo -e "\033[\033[38;5;123mHOST $(hostname)\033[0m"
  sleep 0.3s
  echo -e "\033[\033[38;5;123mANDROID $(neofetch |grep Android|awk '{print $3}')\033[0m"
  echo -e ""
  echo -e "\033[\033[38;5;123m         ┌─────────────────────────┐\033[0m"
  echo -e "\033[\033[38;5;123m         │LINUX               o o o│\033[0m"
  echo -e "\033[\033[38;5;123m         │─────────────────────────│\033[0m"
  echo -e "\033[\033[38;5;123m         │CONTAINER                │\033[0m"
  echo -e "\033[\033[38;5;123m         │~# echo Hello-Word       │\033[0m"
  echo -e "\033[\033[38;5;123m         │Hello-Word┌────────────────────────────────┐\033[0m"
  echo -e "\033[\033[38;5;123m         │~#        │ANDROID                    o o o│──┐\033[0m"
  echo -e "\033[\033[38;5;123m         │          │────────────────────────────────│ o│\033[0m"
  echo -e "\033[\033[38;5;123m         │          │         o            o         │──│\033[0m"
  echo -e "\033[\033[38;5;123m         │          │          o          o          │  │\033[0m"
  echo -e "\033[\033[38;5;123m         └──────────│          +hydNNNNdyh+          │  │\033[0m"
  echo -e "\033[\033[38;5;123m                    │        +mMMMMMMMMMMMMm+        │  │\033[0m"
  echo -e "\033[\033[38;5;123m                    │       dMM::NMMMMMMN::MMd       │  │\033[0m"
  echo -e "\033[\033[38;5;123m                    │      hMMMMMMMMMMMMMMMMMMh      │  │\033[0m"
  echo -e "\033[\033[38;5;123m                    │  ..  yyyyyyyyyyyyyyyyyyyy  ..  │  │\033[0m"
  echo -e "\033[\033[38;5;123m                    │.mMMm MMMMMMMMMMMMMMMMMMMM mMMm.│  │\033[0m"
  echo -e "\033[\033[38;5;123m                    │:MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM:│  │\033[0m"
  echo -e "\033[\033[38;5;123m                    │:MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM:│  │\033[0m"
  echo -e "\033[\033[38;5;123m                    │:MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM:│  │\033[0m"
  echo -e "\033[\033[38;5;123m                    │:MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM:│  │\033[0m"
  echo -e "\033[\033[38;5;123m                    │-MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM-│  │\033[0m"
  echo -e "\033[\033[38;5;123m                    │ +yy+ MMMMMMMMMMMMMMMMMMMM +yy+ │  │\033[0m"
  echo -e "\033[\033[38;5;123m                    │      mMMMMMMMMMMMMMMMMMMm      │  │\033[0m"
  echo -e "\033[\033[38;5;123m                    │       /++MMMMh++hMMMM++/       │  │\033[0m"
  echo -e "\033[\033[38;5;123m                    │          MMMMo  oMMMM          │  │\033[0m"
  echo -e "\033[\033[38;5;123m                    │          MMMMo  oMMMM          │  │\033[0m"
  echo -e "\033[\033[38;5;123m                    │          oNMm-  -mMNs          │  │\033[0m"
  echo -e "\033[\033[38;5;123m                    │ ╔═║  ╔═   ╔═   ╔═║  ╔═║  ╝  ╔═ │  │\033[0m"
  echo -e "\033[\033[38;5;123m                    │ ╔═║  ║ ║  ║ ║  ╔╔╝  ║ ║  ║  ║ ║│  │\033[0m"
  echo -e "\033[\033[38;5;123m                    │ ╝ ╝  ╝ ╝  ══   ╝ ╝  ══╝  ╝  ══ │  │\033[0m"
  echo -e "\033[\033[38;5;123m                    └────────────────────────────────┘  │\033[0m"
  echo -e "\033[\033[38;5;123m                      └─────────────────────────────────┘\033[0m"
  sleep 0.3s
  echo -e ""
  sleep 0.1s
  echo -e "\033[\033[38;5;123m44 72 65 61 6d 2f 77 69 74 68 2f 6d 65 00 00 00 00 00 00 00 00 00 00\033[0m"
  sleep 0.1s
  echo -e "\033[\033[38;5;123m4b 65 65 70 2f 6d 6f 65 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00\033[0m"
  sleep 0.1s
  echo -e "\033[\033[38;5;123m4b 65 65 70 2f 63 6f 6f 6c 00 00 00 00 00 00 00 00 00 00 00 00 00 00\033[0m"
  sleep 0.1s
  echo -e "\033[\033[38;5;123m4b 65 65 70 2f 68 61 63 6b 69 6e 67 00 00 00 00 00 00 00 00 00 00 00\033[0m"
  sleep 0.1s
  echo -e "\033[\033[38;5;123m54 61 6c 6b 2f 69 73 2f 63 68 65 61 70 00 00 00 00 00 00 00 00 00 00\033[0m"
  sleep 0.1s
  echo -e "\033[\033[38;5;123m53 68 6f 77 2f 6d 65 2f 74 68 65 2f 63 6f 64 65 00 00 00 00 00 00 00\033[0m"
  sleep 0.1s
  echo -e "\033[\033[38;5;123m54 6f 2f 62 65 2f 79 6f 75 2f 77 61 6e 74 2f 74 6f 2f 62 65 00 00 00\033[0m"
  sleep 0.1s
  echo -e "\033[\033[38;5;123m54 72 79 2f 65 76 65 72 79 74 68 69 6e 67 00 00 00 00 00 00 00 00 00\033[0m"
  echo -e ""
  sleep 0.1s
  echo -e "\033[\033[38;5;123m//\033[0m"
  echo -e ""
  sleep 0.1s
  echo -e "\033[\033[38;5;123mNEVER SETTLE\033[0m"
  echo -e ""
  sleep 0.1s
  echo -e "\033[\033[38;5;123m//"
  echo -e ""
  sleep 0.s
}
case $TODO in
  unmount)    UNMOUNT;;
  configure)CONFIGURE;;
  update)      UPDATE;;
  mount)        MOUNT;;
  *)        CONTAINER;;
esac
