#!/data/data/com.termux/files/usr/bin/bash
######用于只挂载镜像到指定挂载点而不运行chroot######
[[ ${OUTPUT} = "n" ]] ||clear
[[ ${OUTPUT} = "n" ]] ||echo -e ""
[[ ${OUTPUT} = "n" ]] ||echo -e "\033[\033[38;5;123m//\033[0m"
[[ ${OUTPUT} = "n" ]] ||echo -e ""
[[ ${OUTPUT} = "n" ]] ||sleep 0.1s
[[ ${OUTPUT} = "n" ]] ||echo -e "\033[46;37mMOUNTING                                                              \033[0m"
[[ ${OUTPUT} = "n" ]] ||sleep 0.1s
[[ ${OUTPUT} = "n" ]] ||echo -e ""
[[ ${OUTPUT} = "n" ]] ||echo -e "\033[\033[38;5;123m//\033[0m"
[[ ${OUTPUT} = "n" ]] ||echo -e ""
[[ ${OUTPUT} = "n" ]] ||sleep 0.1s
if [[ ${CHROOT_IMG} = "" ]];then
  echo -e "\033[38;5;123m[ERR!]  Not using image file\033[0m"
  exit
fi
if [[ ! -e ${CHROOT_IMG} ]];then
  echo -e "\033[38;5;123m[ERR!] Image file does not exist \033[0m"
  exit
fi
loop=$(sudo losetup -f)
sudo losetup $loop ${CHROOT_IMG}
sudo mount $loop ${CHROOT_DIR}
echo -e "\033[38;5;123m[INFO] ${CHROOT_IMG} MOUNTED ON ${CHROOT_DIR} \033[0m"
echo -e "\033[38;5;123m[INFO]  DONE\033[0m"
