#!/data/data/com.termux/files/usr/bin/bash
#########用于还原容器#########
clear
echo -e ""
echo -e "\033[38;5;123m//"
echo -e ""
i1=$(($(stty size|awk '{print $2}')))
let i1=$(($i1))
i1=$(($i1-7))
echo -e "\033[46;37mRESTORE$(yes " "|sed $i1'q'|tr -d '\n')\033[0m"
echo -e ""
echo -e "\033[38;5;123m//"
echo -e ""
printf "\033[38;5;123m"
#直接还原到根目录
case $1 in
  *tar.gz) tar -xzvPf $1 -C /;;
  *tar.xz) tar -xvPf $1 -C /;;
  *) echo 'UNKNOW FILE FORMAT';exit 0;;
esac
cd /data/data/com.termux/files/usr/tmp/termux-container
#查找配置
for i1 in {1..100};do
  if [[ ! -e /data/data/com.termux/files/usr/etc/container.conf.d/container-${i1}.conf ]];then
    CONTAINER=$i1
    break
  fi
done
mv container.conf /data/data/com.termux/files/usr/etc/container.conf.d/container-${i1}.conf
rm /data/data/com.termux/files/usr/etc/container.conf
printf "\033[0m"
echo CONTAINER=${CONTAINER} >> /data/data/com.termux/files/usr/etc/container.conf
#   │  │   ╔══╝╔══║╔══╝
# ── ── ── ║   ║  ║║
#   │  │   ╔══╝║  ║╔══╝
# ── ── ── ║   ║  ║║
#   │  │   ═══╝═══╝╝
