#!/data/data/com.termux/files/usr/bin/bash
#########用于更新此脚本#########
export $(cat /data/data/com.termux/files/usr/etc/container.conf) >> /dev/null
export $(cat /data/data/com.termux/files/usr/etc/container.conf.d/container-${CONTAINER}.conf) >> /dev/null
clear
echo -e ""
echo -e "\033[38;5;123m//"
echo -e ""
i1=$(($(stty size|awk '{print $2}')))
let i1=$(($i1))
i1=$(($i1-9))
echo -e "\033[46;37mUPDATEING$(yes " "|sed $i1'q'|tr -d '\n')\033[0m"
echo -e ""
echo -e "\033[38;5;123m//"
echo -e ""
cd /data/data/com.termux/files/usr/share/termux-container
echo -e "\033[38;5;123m$(git reset --hard)"
echo -e "\033[38;5;123m$(git pull)"
rm /data/data/com.termux/files/usr/bin/container
cp ./container /data/data/com.termux/files/usr/bin/
chmod 777 /data/data/com.termux/files/usr/bin/container
