#!/data/data/com.termux/files/usr/bin/bash
#########用于容器安装#########
clear
echo -e ""
echo -e "\033[38;5;123m//"
echo -e ""
i1=$(($(stty size|awk '{print $2}')))
let i1=$(($i1))
i1=$(($i1-9))
echo -e "\033[46;37mCONFIGURE$(yes " "|sed $i1'q'|tr -d '\n')\033[0m"
echo -e ""
echo -e "\033[38;5;123m//"
echo -e ""
sleep 0.1s
CONFIGURE(){
  if [[ ! -e /data/data/com.termux/files/usr/etc/container.conf.d ]];then
    mkdir -p /data/data/com.termux/files/usr/etc/container.conf.d
  fi
  #遍历获取未使用的配置文件
  for i1 in {1..100};do
    if [[ ! -e /data/data/com.termux/files/usr/etc/container.conf.d/container-${i1}.conf ]];then
      CONTAINER=$i1
      break
    fi
  done
  printf  "\033[38;5;123m"
  read -p "ENTER THE NAME OF THIS CONTAINER: " NAME
  read -p "ENTER THE ABSOLUTE PATH OF THIS CONTAINER: " CHROOT_DIR
  read -p "DO YOU WANT TO INSTALL THIS CONTAINER IN AN IMAGE FILE [y/n]?" USE_IMAGE
  if [[ ${USE_IMAGE} = "y" ]];then
    read -p "ENTER THE ABSOLUTE PATH OF IMAGE FILE: " CHROOT_IMG_PATH
    read -p "ENTER THE NAME OF IMAGE FILE: " CHROOT_IMG_NAME
    read -p "ENTER THE SIZE OF IMAGE FILE(UNIT IS GB): " SIZE
  fi
  read -p "ENTER THE ROOTFS DOWNLOAD LINK: " URL
  read -p "DISABLE SELinux?[y/n]: " SELINUX
  read -p "ENTER YOUR HOSTNAME: " HOSTNAME
  read -p "ENABLE OUTPUT?[y/n]: " OUTPUT
  echo -e "CHOOSE YOUR CUSOR: "
  read -p '[1]: $|   [2]: $▂   [3]: $█ ' CUSOR
  #简化输入
  case ${CUSOR} in
    1) CUSOR=bar;;
    2) CUSOR=underline;;
    3) CUSOR=block;;
  esac
  echo -e "DOWNLOADING ROOTFS"
  sleep 1s
  rm -rf /data/data/com.termux/files/usr/tmp/container >/dev/null 2>&1
  mkdir -p /data/data/com.termux/files/usr/tmp/container >/dev/null 2>&1
  cd /data/data/com.termux/files/usr/tmp/container >/dev/null 2>&1
  #下载rootfs
  wget ${URL}
  sudo mkdir -p ${CHROOT_DIR}
  if [[ ! ${CHROOT_IMG_NAME} = "" ]];then  #创建img镜像并挂载
    echo -e "CREATING IMAGE FILE"
    sudo mkdir -p ${CHROOT_IMG_PATH}
    cd ${CHROOT_IMG_PATH}
    sudo dd if=/dev/zero of=${CHROOT_IMG_NAME}.img bs=1G count=${SIZE}
    sudo mkfs.ext4 ${CHROOT_IMG_NAME}.img
    echo -e "MOUNTING IMAGE FILE"
    sleep 1s
    LOOP=$(sudo losetup -f)
    sudo losetup  ${LOOP} ${CHROOT_IMG_NAME}.img  >/dev/null 2>&1
    sudo mount ${LOOP} ${CHROOT_DIR}  >/dev/null 2>&1
  fi
  echo -e "EXTRACTING ROOTFS"
  sleep 2s
  #解压rootfs
  ROOTFS=$(ls /data/data/com.termux/files/usr/tmp/container/)
  case $ROOTFS in
    *tar.gz|*tgz|*tar) tar -xzvf /data/data/com.termux/files/usr/tmp/container/$ROOTFS -C ${CHROOT_DIR};;
    *tar.xz|*txz) tar -xvf /data/data/com.termux/files/usr/tmp/container/$ROOTFS -C ${CHROOT_DIR};;
    *) echo 'UNKNOW FILE FORMAT';exit 0;;
  esac
  echo -e ""
  echo -e "\033[38;5;123mWRITING CONFIGURE FILE"
  sleep 1s
  #写入配置
  echo NAME=${NAME} >> /data/data/com.termux/files/usr/etc/container.conf.d/container-${CONTAINER}.conf
  echo CUSOR=${CUSOR} >> /data/data/com.termux/files/usr/etc/container.conf.d/container-${CONTAINER}.conf
  echo CHROOT_DIR=${CHROOT_DIR} >> /data/data/com.termux/files/usr/etc/container.conf.d/container-${CONTAINER}.conf
  echo CHROOT_IMG=${CHROOT_IMG_PATH}/${CHROOT_IMG_NAME}.img >> /data/data/com.termux/files/usr/etc/container.conf.d/container-${CONTAINER}.conf
  echo SELinux=${SELINUX} >> /data/data/com.termux/files/usr/etc/container.conf.d/container-${CONTAINER}.conf
  echo OUTPUT=${OUTPUT} >> /data/data/com.termux/files/usr/etc/container.conf.d/container-${CONTAINER}.conf
  echo HOSTNAME=${HOSTNAME} >> /data/data/com.termux/files/usr/etc/container.conf.d/container-${CONTAINER}.conf
  rm -f /data/data/com.termux/files/usr/etc/container.conf
  echo CONTAINER=${CONTAINER} >> /data/data/com.termux/files/usr/etc/container.conf
  echo -e "REMOVING DOWNLOADED ROOTFS\033[0m"
  sleep 1s
  #清空tmp
  rm -rf /data/data/com.termux/files/usr/tmp/container
}
SET(){
  cd /data/data/com.termux/files/usr/etc/container.conf.d
  for i in {1..100};do
    if [[ -e container-${i}.conf ]];then
      export $(cat container-${i}.conf)
      echo -e "\033[38;5;123m[$i] $NAME"
    fi
  done
  read -p "SELECT A CONTAINER: " CONTAINER
  rm -f /data/data/com.termux/files/usr/etc/container.conf
  echo CONTAINER=${CONTAINER} >> /data/data/com.termux/files/usr/etc/container.conf
}
case $1 in
  set) SET;;
  *)   CONFIGURE;;
esac
