#!/data/data/com.termux/files/usr/bin/bash
#########用于备份容器#########
printf "\033[38;5;123m"
cd /data/data/com.termux/files/usr/etc/container.conf.d
for i in {1..100};do
  if [[ -e container-${i}.conf ]];then
    export $(cat container-${i}.conf)
    echo -e "[$i] $NAME"
    sleep 0.3s
  fi
done
read -p "SELECT A CONTAINER TO BACKUP: " CONTAINER
export $(cat /data/data/com.termux/files/usr/etc/container.conf.d/container-${CONTAINER}.conf)
#解除挂载
echo -e "UNMOUNTING"
echo -e "[START] UNMOUNT /dev"
umount -lvf ${CHROOT_DIR}/dev >/dev/null 2>&1 #解除/dev的挂载
echo -e "[DONE ] UNMOUNT /dev"
echo -e "[START] UNMOUNT /sys"
umount -lvf ${CHROOT_DIR}/sys >/dev/null 2>&1 #解除/sys的挂载
echo -e "[DONE ] UNMOUNT /sys"
echo -e "[START] UNMOUNT /proc"
umount -lvf ${CHROOT_DIR}/proc >/dev/null 2>&1 #解除/proc挂载
echo -e "[DONE ] UNMOUNT /proc"
echo -e "[START] UNMOUNT /sdcard"
umount ${CHROOT_DIR}/sdcard >/dev/null 2>&1 #解除/sdcard的挂载
echo -e "[DONE ] UNMOUNT /sdcard"
echo -e "[START] UNMOUNT ${CHROOT_DIR}"
umount -lvf ${CHROOT_DIR} >/dev/null 2>&1 #解除目录自身挂载
losetup -d ${CHROOT_IMG} >/dev/null 2>&1 #解除img镜像与虚拟设备的关联
echo -e "[DONE ] UNMOUNT ${CHROOT_DIR}"
mkdir -p /data/data/com.termux/files/usr/tmp/termux-container
cp container-${CONTAINER}.conf /data/data/com.termux/files/usr/tmp/termux-container/container.conf
clear
#选择格式
echo -e "CHOOSE THE FILE FORMAT: "
read -p "[1]tar.gz [2]tar.xz" FORMAT
#判断备份文件是否存在
if [[ -e /sdcard/container-${NAME}.tar.gz ]];then
  mv /sdcard/container-${NAME}.tar.gz /sdcard/container-${NAME}-bk.tar.gz
fi
#备份
if [[ ${CHROOT_IMG} != "" ]];then
  case ${FORMAT} in
   1) tar -zcvf /sdcard/container-${NAME}.tar.gz ${CHROOT_IMG} ${CHROOT_DIR} /data/data/com.termux/files/usr/tmp/termux-container ;;
   2) tar -Jcvf /sdcard/container-${NAME}.tar.xz ${CHROOT_IMG} ${CHROOT_DIR} /data/data/com.termux/files/usr/tmp/termux-container ;;
  esac
else
  case ${FORMAT} in
    1) tar -zcvf /sdcard/container-${NAME}.tar.gz ${CHROOT_DIR} /data/data/com.termux/files/usr/tmp/termux-container ;;
    2) tar -Jcvf /sdcard/container-${NAME}.tar.xz ${CHROOT_DIR} /data/data/com.termux/files/usr/tmp/termux-container ;;
  esac
fi

