#!/data/data/com.termux/files/usr/bin/bash
#########用于备份容器#########
#${CONTAINER}是配置文件编号
clear
#没用的输出
echo -e "\033[38;5;123m"
echo -e "//"
echo -e ""
i1=$(($(stty size|awk '{print $2}')))
let i1=$(($i1))
i1=$(($i1-16))
echo -e "\033[46;37mCONTAINER_BACKUP$(yes " "|sed $i1'q'|tr -d '\n')\033[0m"
echo -e "\033[38;5;123m"
echo -e "//"
echo -e ""
cd /data/data/com.termux/files/usr/etc/container.conf.d
#遍历查找配置文件
for i in {1..100};do
  if [[ -e container-${i}.conf ]];then
    export $(cat container-${i}.conf)
    echo -e "[$i] $NAME"
    sleep 0.3s
  fi
done
read -p "SELECT A CONTAINER TO BACKUP: " CONTAINER
export $(cat /data/data/com.termux/files/usr/etc/container.conf.d/container-${CONTAINER}.conf)
#解除挂载
echo -e "UNMOUNTING"
echo -e "[START] UNMOUNT /dev"
umount -lvf ${CHROOT_DIR}/dev >/dev/null 2>&1 #解除/dev的挂载
echo -e "[DONE ] UNMOUNT /dev"
echo -e "[START] UNMOUNT /sys"
umount -lvf ${CHROOT_DIR}/sys >/dev/null 2>&1 #解除/sys的挂载
echo -e "[DONE ] UNMOUNT /sys"
echo -e "[START] UNMOUNT /proc"
umount -lvf ${CHROOT_DIR}/proc >/dev/null 2>&1 #解除/proc挂载
echo -e "[DONE ] UNMOUNT /proc"
echo -e "[START] UNMOUNT /sdcard"
umount ${CHROOT_DIR}/sdcard >/dev/null 2>&1 #解除/sdcard的挂载
echo -e "[DONE ] UNMOUNT /sdcard"
echo -e "[START] UNMOUNT ${CHROOT_DIR}"
umount -lvf ${CHROOT_DIR} >/dev/null 2>&1 #解除目录自身挂载
losetup -d ${CHROOT_IMG} >/dev/null 2>&1 #解除img镜像与虚拟设备的关联
echo -e "[DONE ] UNMOUNT ${CHROOT_DIR}"
#移动配置文件，不直接备份防止还原时覆盖其他容器配置
mkdir -p /data/data/com.termux/files/usr/tmp/termux-container
cp container-${CONTAINER}.conf /data/data/com.termux/files/usr/tmp/termux-container/container.conf
clear
#选择格式
echo -e "CHOOSE THE FILE FORMAT: "
read -p "[1]tar.gz [2]tar.xz " FORMAT
#判断备份文件是否存在
if [[ -e /sdcard/container-${NAME}.tar.gz ]];then
  mv /sdcard/container-${NAME}.tar.gz /sdcard/container-${NAME}-bk.tar.gz
fi
#备份,使用tar
if [[ ${CHROOT_IMG} != "" ]];then
  case ${FORMAT} in
    1) tar -zcvPf /sdcard/container-${NAME}.tar.gz ${CHROOT_IMG} ${CHROOT_DIR} /data/data/com.termux/files/usr/tmp/termux-container ;;
    2) tar -JcvPf /sdcard/container-${NAME}.tar.xz ${CHROOT_IMG} ${CHROOT_DIR} /data/data/com.termux/files/usr/tmp/termux-container ;;
  esac
else
  case ${FORMAT} in
    1) tar -zcvPf /sdcard/container-${NAME}.tar.gz ${CHROOT_DIR} /data/data/com.termux/files/usr/tmp/termux-container ;;
    2) tar -JcvPf /sdcard/container-${NAME}.tar.xz ${CHROOT_DIR} /data/data/com.termux/files/usr/tmp/termux-container ;;
  esac
fi
#   │  │   ╔══╝╔══║╔══╝
# ── ── ── ║   ║  ║║
#   │  │   ╔══╝║  ║╔══╝
# ── ── ── ║   ║  ║║
#   │  │   ═══╝═══╝╝

