#!/data/data/com.termux/files/usr/bin/bash
######用于只挂载镜像到指定挂载点而不运行chroot######
export $(cat /data/data/com.termux/files/usr/etc/container.conf) #加载配置文件
if [[ ${CHROOT_IMG} = "" ]];then
  echo -e "\033[38;5;123m[ERR!]  Not using image file\033[0m"
  exit
fi
if [[ ! -e ${CHROOT_IMG} ]];then
  echo -e "\033[38;5;123m[ERR!] Image file does not exist \033[0m"
  exit
fi
loop=$(sudo losetup -f)
sudo losetup $loop ${CHROOT_IMG}
sudo mount $loop ${CHROOT_DIR}
echo -e "\033[38;5;123m[INFO] ${CHROOT_IMG} MOUNTED ON ${CHROOT_DIR} \033[0m"
echo -e "\033[38;5;123m[INFO]  DONE\033[0m"
