MAINTAINER Moe-hacker <moe-hacker@outlook.com>
#*
NAME test
DESC test containerfile for termux-container
#*
TYPE proot
ARCH arm64
#*
FROM alpine:edge
ADD "https://example.com/example" /tmp/example
RUN ls
RUN echo hello
