#!/data/data/com.termux/files/usr/bin/bash
# SPDX-License-Identifier: Apache-2.0
# This file is part of termux-container.
#
# Copyright (c) 2023 Moe-hacker
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#TODO:测试
if [[ -e $PREFIX/etc/container/global.conf ]];then
  echo -e "\033[1;38;2;254;228;208mUpgrade script for termux-container v8 to v9."
  echo -e "This script will automatically detecte the old config file and try to convert them to the new version."
  read -p "Press Enter to continue." x
  cp -rf $PREFIX/etc/container/ $PREFIX/etc/container.bk
  source $PREFIX/etc/container/global.conf
  for i in $(ls $PREFIX/etc/container/container-*.conf)
  do
    source $i
    if [[ $RUN_MODE == "chroot-unshare" ]];then
      [[ -e $PREFIX/etc/container/chroot ]]||mkdir -p $PREFIX/etc/container/chroot
      if [[ ! -e $PREFIX/etc/container/chroot/container-${NAME}.conf ]]&&[[ ! -e $PREFIX/etc/container/proot/container-${NAME}.conf ]];then
        echo "CONTAINER_NAME=${NAME}" >> $PREFIX/etc/container/chroot/container-${NAME}.conf
        echo "CONTAINER_DIR=${CONTAINER_DIR}" >> $PREFIX/etc/container/chroot/container-${NAME}.conf
        echo "MOUNT_SDCARD=${MOUNT_SDCARD}" >> $PREFIX/etc/container/chroot/container-${NAME}.conf
        echo "PRIVAGE_LEVEL=2" >> $PREFIX/etc/container/chroot/container-${NAME}.conf
        echo "ENABLE_UNSHARE=true" >> $PREFIX/etc/container/chroot/container-${NAME}.conf
      else
        echo -e "Cntainer name ${NAME} already in use,so you need to rename it now."
        while :
        do
          read -p "Name: " NAME
          [[ ! -e $PREFIX/etc/container/chroot/container-${NAME}.conf ]]&&[[ ! -e $PREFIX/etc/container/proot/container-${NAME}.conf ]]&&break
        done
        echo "CONTAINER_NAME=${NAME}" >> $PREFIX/etc/container/chroot/container-${NAME}.conf
        echo "CONTAINER_DIR=${CONTAINER_DIR}" >> $PREFIX/etc/container/chroot/container-${NAME}.conf
        echo "MOUNT_SDCARD=${MOUNT_SDCARD}" >> $PREFIX/etc/container/chroot/container-${NAME}.conf
        echo "PRIVAGE_LEVEL=2" >> $PREFIX/etc/container/chroot/container-${NAME}.conf
        echo "ENABLE_UNSHARE=true" >> $PREFIX/etc/container/chroot/container-${NAME}.conf
      fi
    else
      [[ -e $PREFIX/etc/container/proot ]]||mkdir -p $PREFIX/etc/container/proot
      if [[ ! -e $PREFIX/etc/container/proot/container-${NAME}.conf ]]&&[[ ! -e $PREFIX/etc/container/chroot/container-${NAME}.conf ]];then
        echo "CONTAINER_NAME=${NAME}" >> $PREFIX/etc/container/proot/container-${NAME}.conf
        echo "CONTAINER_DIR=${CONTAINER_DIR}" >> $PREFIX/etc/container/proot/container-${NAME}.conf
        echo "MOUNT_SDCARD=${MOUNT_SDCARD}" >> $PREFIX/etc/container/proot/container-${NAME}.conf
        echo "CROSS_ARCH=${CROSS_ARCH}" >> $PREFIX/etc/container/proot/container-${NAME}.conf
      else
        echo -e "Cntainer name ${NAME} already in use,so you need to rename it now."
        while :
        do
          read -p "Name: " NAME
          [[ ! -e $PREFIX/etc/container/proot/container-${NAME}.conf ]]&&[[ ! -e $PREFIX/etc/container/chroot/container-${NAME}.conf ]]&&break
        done
        echo "CONTAINER_NAME=${NAME}" >> $PREFIX/etc/container/proot/container-${NAME}.conf
        echo "CONTAINER_DIR=${CONTAINER_DIR}" >> $PREFIX/etc/container/proot/container-${NAME}.conf
        echo "MOUNT_SDCARD=${MOUNT_SDCARD}" >> $PREFIX/etc/container/proot/container-${NAME}.conf
        echo "CROSS_ARCH=${CROSS_ARCH}" >> $PREFIX/etc/container/proot/container-${NAME}.conf
      fi
    fi
  done
  rm $PREFIX/etc/container/global.conf
  rm $PREFIX/etc/container/container-*.conf
fi
echo -e "\033[33mWarning:"
echo -e "[] If this is not a ubuntu logo,please run:"
echo "mkdir -p ~/.termux"
echo "cp \$PREFIX/share/termux-container/font.ttf ~/.termux"
echo "termux-reload-settings"
RGB_COLOR="254;228;208"
COLOR="\033[1;38;2;${RGB_COLOR}m"
x="${COLOR}  .^.   .^.
  /⋀\_ﾉ_/⋀\\
 /ﾉｿﾉ\ﾉｿ丶)|
|ﾙﾘﾘ >   )ﾘ
ﾉノ㇏  ω ﾉ|ﾉ
      ⠁⠁
Enjoy, nya~"
printf "$x\n"

