#!/data/data/com.termux/files/usr/bin/bash
# SPDX-License-Identifier: Apache-2.0
# This file is part of termux-container.
#
# Copyright (c) 2023 Moe-hacker
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
echo -e "\033[33mWarning:"
echo -e "[] If this is not a ubuntu logo,please run:"
echo "mkdir -p ~/.termux"
echo "cp \$PREFIX/share/termux-container/font.ttf ~/.termux"
echo "termux-reload-settings"
RGB_COLOR="254;228;208"
COLOR="\033[1;38;2;${RGB_COLOR}m"
x="${COLOR}  .^.   .^.
  /⋀\_ﾉ_/⋀\\
 /ﾉｿﾉ\ﾉｿ丶)|
|ﾙﾘﾘ >   )ﾘ
ﾉノ㇏  ω ﾉ|ﾉ
      ⠁⠁
Enjoy, nya~"
printf "$x\n"

