#!/bin/sh
# ██╗ ██╗  ██╗ ███████╗ ██╗  ██╗
#████████╗ ██║ ██╔════╝ ██║  ██║
#╚██╔═██╔╝ ██║ ███████╗ ███████║
#████████╗ ╚═╝ ╚════██║ ██╔══██║
#╚██╔═██╔╝ ██╗ ███████║ ██║  ██║
# ╚═╝ ╚═╝  ╚═╝ ╚══════╝ ╚═╝  ╚═╝
###### Github@Moe-hacker ######
export PATH="/bin:/usr/bin:/usr/local/bin"
if [ -e /etc/enable_output ];then
  export ENABLE_OUTPUT=y
else
  export ENABLE_OUTPUT=n
fi
####################
######日志管理######
####################
rm -f /tmp/init.log
export LOG_FILE="/tmp/init.log"
CONTAINER_LOG(){
  /bin/echo -e "[$(date +%Y-%m-%d\ %H:%M:%S)] $@" >> ${LOG_FILE}
}
####################
######挂载目录######
####################
CONTAINER_LOG "MOUNT /proc"
mount -t proc proc -o rw,nosuid,nodev,noexec,relatime /proc >> ${LOG_FILE} 2>&1
[ ${ENABLE_OUTPUT} = "n" ]||/bin/echo -e "\033[38;5;159m[\033[38;5;158m\033[38;5;159m] MOUNT /proc"
[ ${ENABLE_OUTPUT} = "n" ]||sleep 0.1s
CONTAINER_LOG "MOUNT /sys"
mount -t sysfs sysfs -o ro,seclabel,nosuid,nodev,noexec,relatime /sys >> ${LOG_FILE} 2>&1
[ ${ENABLE_OUTPUT} = "n" ]||/bin/echo -e "\033[38;5;159m[\033[38;5;158m\033[38;5;159m] MOUNT /sys"
[ ${ENABLE_OUTPUT} = "n" ]||sleep 0.1s
CONTAINER_LOG "MOUNT /dev"
mount -t tmpfs tmpfs -o rw,seclabel,nosuid,size=65536k,mode=755 /dev >> ${LOG_FILE} 2>&1
[ ${ENABLE_OUTPUT} = "n" ]||/bin/echo -e "\033[38;5;159m[\033[38;5;158m\033[38;5;159m] MOUNT /dev"
[ ${ENABLE_OUTPUT} = "n" ]||sleep 0.1s
####################
######创建设备######
####################
CONTAINER_LOG "CREATE /dev/console"
mknod -m 622 /dev/console c 5 1 >> ${LOG_FILE} 2>&1
[ ${ENABLE_OUTPUT} = "n" ]||/bin/echo -e "\033[38;5;159m[\033[38;5;158m\033[38;5;159m] CREATE /dev/console"
[ ${ENABLE_OUTPUT} = "n" ]||sleep 0.1s
CONTAINER_LOG "CHOWN /dev/console"
chown root:tty /dev/console >> ${LOG_FILE} 2>&1
[ ${ENABLE_OUTPUT} = "n" ]||/bin/echo -e "\033[38;5;159m[\033[38;5;158m\033[38;5;159m] CHOWN /dev/console"
[ ${ENABLE_OUTPUT} = "n" ]||sleep 0.1s
CONTAINER_LOG "CREATE /dev/null"
mknod -m 666 /dev/null c 1 3 >> ${LOG_FILE} 2>&1
[ ${ENABLE_OUTPUT} = "n" ]||/bin/echo -e "\033[38;5;159m[\033[38;5;158m\033[38;5;159m] CREATE /dev/null"
[ ${ENABLE_OUTPUT} = "n" ]||sleep 0.1s
CONTAINER_LOG "CREATE /dev/zero"
mknod -m 666 /dev/zero c 1 5 >> ${LOG_FILE} 2>&1
[ ${ENABLE_OUTPUT} = "n" ]||/bin/echo -e "\033[38;5;159m[\033[38;5;158m\033[38;5;159m] CREATE /dev/zero"
[ ${ENABLE_OUTPUT} = "n" ]||sleep 0.1s
CONTAINER_LOG "CREATE /dev/ptmx"
mknod -m 666 /dev/ptmx c 5 2 >> ${LOG_FILE} 2>&1
[ ${ENABLE_OUTPUT} = "n" ]||/bin/echo -e "\033[38;5;159m[\033[38;5;158m\033[38;5;159m] CREATE /dev/ptmx"
[ ${ENABLE_OUTPUT} = "n" ]||sleep 0.1s
CONTAINER_LOG "CHOWN /dev/ptmx"
chown root:tty /dev/ptmx >> ${LOG_FILE} 2>&1
[ ${ENABLE_OUTPUT} = "n" ]||/bin/echo -e "\033[38;5;159m[\033[38;5;158m\033[38;5;159m] CHOWN /dev/ptmx"
[ ${ENABLE_OUTPUT} = "n" ]||sleep 0.1s
CONTAINER_LOG "CREATE /dev/tty"
mknod -m 666 /dev/tty c 5 0 >> ${LOG_FILE} 2>&1
[ ${ENABLE_OUTPUT} = "n" ]||/bin/echo -e "\033[38;5;159m[\033[38;5;158m\033[38;5;159m] CREATE /dev/tty"
[ ${ENABLE_OUTPUT} = "n" ]||sleep 0.1s
CONTAINER_LOG "CHOWN /dev/tty"
chown root:tty /dev/tty >> ${LOG_FILE} 2>&1
[ ${ENABLE_OUTPUT} = "n" ]||/bin/echo -e "\033[38;5;159m[\033[38;5;158m\033[38;5;159m] CHOWN /dev/tty"
[ ${ENABLE_OUTPUT} = "n" ]||sleep 0.1s
CONTAINER_LOG "CREATE /dev/random"
mknod -m 444 /dev/random c 1 8 >> ${LOG_FILE} 2>&1
[ ${ENABLE_OUTPUT} = "n" ]||/bin/echo -e "\033[38;5;159m[\033[38;5;158m\033[38;5;159m] CREATE /dev/random"
[ ${ENABLE_OUTPUT} = "n" ]||sleep 0.1s
CONTAINER_LOG "CREATE /dev/urandom"
mknod -m 444 /dev/urandom c 1 9 >> ${LOG_FILE} 2>&1
[ ${ENABLE_OUTPUT} = "n" ]||/bin/echo -e "\033[38;5;159m[\033[38;5;158m\033[38;5;159m] CREATE /dev/urandom"
[ ${ENABLE_OUTPUT} = "n" ]||sleep 0.1s
CONTAINER_LOG "CREATE /dev/fd"
ln -s /proc/self/fd /dev/fd >> ${LOG_FILE} 2>&1
[ ${ENABLE_OUTPUT} = "n" ]||/bin/echo -e "\033[38;5;159m[\033[38;5;158m\033[38;5;159m] CREATE /dev/fd"
[ ${ENABLE_OUTPUT} = "n" ]||sleep 0.1s
CONTAINER_LOG "CREATE /dev/stdin"
ln -s /proc/self/fd/0 /dev/stdin >> ${LOG_FILE} 2>&1
[ ${ENABLE_OUTPUT} = "n" ]||/bin/echo -e "\033[38;5;159m[\033[38;5;158m\033[38;5;159m] CREATE /dev/stdin"
[ ${ENABLE_OUTPUT} = "n" ]||sleep 0.1s
CONTAINER_LOG "CREATE /dev/stdout"
ln -s /proc/self/fd/1 /dev/stdout >> ${LOG_FILE} 2>&1
[ ${ENABLE_OUTPUT} = "n" ]||/bin/echo -e "\033[38;5;159m[\033[38;5;158m\033[38;5;159m] CREATE /dev/stdout"
[ ${ENABLE_OUTPUT} = "n" ]||sleep 0.1s
CONTAINER_LOG "CREATE /dev/stderr"
ln -s /proc/self/fd/2 /dev/stderr >> ${LOG_FILE} 2>&1
[ ${ENABLE_OUTPUT} = "n" ]||/bin/echo -e "\033[38;5;159m[\033[38;5;158m\033[38;5;159m] CREATE /dev/stderr"
[ ${ENABLE_OUTPUT} = "n" ]||sleep 0.1s
CONTAINER_LOG "CREATE /dev/tty0"
ln -s /dev/null /dev/tty0 >> ${LOG_FILE} 2>&1
[ ${ENABLE_OUTPUT} = "n" ]||/bin/echo -e "\033[38;5;159m[\033[38;5;158m\033[38;5;159m] CREATE /dev/tty0"
[ ${ENABLE_OUTPUT} = "n" ]||sleep 0.1s
CONTAINER_LOG "CREATE /dev/pts"
mkdir /dev/pts >> ${LOG_FILE} 2>&1
mount -t devpts -o gid=4,mode=620 devpts /dev/pts >> ${LOG_FILE} 2>&1
[ ${ENABLE_OUTPUT} = "n" ]||/bin/echo -e "\033[38;5;159m[\033[38;5;158m\033[38;5;159m] CREATE /dev/pts"
[ ${ENABLE_OUTPUT} = "n" ]||sleep 0.1s
CONTAINER_LOG "CREATE /dev/shm"
mkdir /dev/shm >> ${LOG_FILE} 2>&1
mount -o rw,nosuid,nodev,mode=1777 -t tmpfs tmpfs /dev/shm >> ${LOG_FILE} 2>&1
[ ${ENABLE_OUTPUT} = "n" ]||/bin/echo -e "\033[38;5;159m[\033[38;5;158m\033[38;5;159m] CREATE /dev/shm"
[ ${ENABLE_OUTPUT} = "n" ]||sleep 0.1s
CONTAINER_LOG "CREATE /dev/mqueue"
mkdir /dev/mqueue >> ${LOG_FILE} 2>&1
mount -t mqueue none /dev/mqueue >> ${LOG_FILE} 2>&1
[ ${ENABLE_OUTPUT} = "n" ]||/bin/echo -e "\033[38;5;159m[\033[38;5;158m\033[38;5;159m] CREATE /dev/mqueue"
[ ${ENABLE_OUTPUT} = "n" ]||sleep 0.1s
CONTAINER_LOG "CREATE /dev/net/tun"
mkdir /dev/net >> ${LOG_FILE} 2>&1
mknod /dev/net/tun c 10 200 >> ${LOG_FILE} 2>&1
[ ${ENABLE_OUTPUT} = "n" ]||/bin/echo -e "\033[38;5;159m[\033[38;5;158m\033[38;5;159m] CREATE /dev/net/tun"
[ ${ENABLE_OUTPUT} = "n" ]||sleep 0.1s
CONTAINER_LOG "MOUNT /proc/sysrq-trigger AS READ-ONLY FILE SYSTEM"
mount -o bind,private,ro /proc/sysrq-trigger /proc/sysrq-trigger >> ${LOG_FILE} 2>&1
[ ${ENABLE_OUTPUT} = "n" ]||/bin/echo -e "\033[38;5;159m[\033[38;5;158m\033[38;5;159m] MOUNT /proc/sysrq-trigger"
[ ${ENABLE_OUTPUT} = "n" ]||sleep 0.1s
CONTAINER_LOG "MOUNT /proc/bus AS READ-ONLY FILE SYSTEM"
mount -o bind,ro,relatime /proc/bus /proc/bus
[ ${ENABLE_OUTPUT} = "n" ]||/bin/echo -e "\033[38;5;159m[\033[38;5;158m\033[38;5;159m] MOUNT /proc/bus"
[ ${ENABLE_OUTPUT} = "n" ]||sleep 0.1s
CONTAINER_LOG "MOUNT /proc/fs AS READ-ONLY FILE SYSTEM"
mount -o bind,ro,relatime /proc/fs /proc/fs
[ ${ENABLE_OUTPUT} = "n" ]||/bin/echo -e "\033[38;5;159m[\033[38;5;158m\033[38;5;159m] MOUNT /proc/fs"
[ ${ENABLE_OUTPUT} = "n" ]||sleep 0.1s
CONTAINER_LOG "MOUNT /proc/irq AS READ-ONLY FILE SYSTEM"
mount -o bind,ro,relatime /proc/irq /proc/irq
[ ${ENABLE_OUTPUT} = "n" ]||/bin/echo -e "\033[38;5;159m[\033[38;5;158m\033[38;5;159m] MOUNT /proc/irq"
[ ${ENABLE_OUTPUT} = "n" ]||sleep 0.1s
CONTAINER_LOG "MOUNT /proc/sys AS READ-ONLY FILE SYSTEM"
mount -o bind,ro,relatime /proc/sys /proc/sys
[ ${ENABLE_OUTPUT} = "n" ]||/bin/echo -e "\033[38;5;159m[\033[38;5;158m\033[38;5;159m] MOUNT /proc/sys"
[ ${ENABLE_OUTPUT} = "n" ]||sleep 0.1s
CONTAINER_LOG "MOUNT /proc/asound AS READ-ONLY FILE SYSTEM"
mount -o bind,ro,seclabel,relatime  /proc/asound /proc/asound
[ ${ENABLE_OUTPUT} = "n" ]||/bin/echo -e "\033[38;5;159m[\033[38;5;158m\033[38;5;159m] MOUNT /proc/asound"
[ ${ENABLE_OUTPUT} = "n" ]||sleep 0.1s
CONTAINER_LOG "MOUNT /proc/scsi AS READ-ONLY FILE SYSTEM"
mount -o bind,ro,seclabel,relatime /proc/scsi /proc/scsi
[ ${ENABLE_OUTPUT} = "n" ]||/bin/echo -e "\033[38;5;159m[\033[38;5;158m\033[38;5;159m] MOUNT /proc/scsi"
[ ${ENABLE_OUTPUT} = "n" ]||sleep 0.1s
CONTAINER_LOG "MOUNT /proc/firmware AS READ-ONLY FILE SYSTEM"
mount -o bind,ro,seclabel,relatime /sys/firmware /sys/firmware
[ ${ENABLE_OUTPUT} = "n" ]||/bin/echo -e "\033[38;5;159m[\033[38;5;158m\033[38;5;159m] MOUNT /sys/firmware"
[ ${ENABLE_OUTPUT} = "n" ]||sleep 0.1s
####################
######设置名称######
####################
#设置主机名
if [ $(hostname) != $(cat /etc/hostname) ];then
  CONTAINER_LOG "SET HOSTNAME"
  hostname $(cat /etc/hostname) >> ${LOG_FILE} 2>&1
  [ ${ENABLE_OUTPUT} = "n" ]||/bin/echo -e "\033[38;5;159m[\033[38;5;158m\033[38;5;159m] SET HOSTNAME"
  [ ${ENABLE_OUTPUT} = "n" ]||sleep 0.1s
fi
####################
######切换用户######
####################
#切换为容器中的root用户
CONTAINER_LOG "LOGIN AS ROOT"
[ ${ENABLE_OUTPUT} = "n" ]||/bin/echo -e "\033[38;5;159m[\033[38;5;158m\033[38;5;159m] LOGIN"
[ ${ENABLE_OUTPUT} = "n" ]||sleep 0.1s
printf "\033[0m"
/bin/su - root
