#!/data/data/com.termux/files/usr/bin/bash
# Copyright 2024 moe-hacker
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
function check_if_succeed() {
  if [[ $1 -ne 0 ]]; then
    echo -e "\033[31mDaijin got an error\033[0m"
    exit 1
  fi
}
function select_range() {
  read -p "$1" range
  if [[ "" == $range ]]; then
    echo $(select_range "$1" $2 $3)
    return
  fi
  if [[ $range -lt $2 || $range -gt $3 ]]; then
    echo $(select_range "$1" $2 $3)
    return
  fi
  echo $range
}
mkdir -p /data/data/com.termux/files/usr/etc/daijin
mkdir -p /data/data/com.termux/files/usr/var/daijin
export VERSION="1.5"
if command -v su >/dev/null; then
  if su -c true; then
    ROOTED=true
    sudo chmod 777 /data/data/com.termux/files/usr/var/daijin/containers
  fi
fi
echo -e "\033[32mDaijin v${VERSION}\033[0m"
echo -e "[1] install\n[2] run\n[3] remove\n[4] register\n[5] clean rootfs\n[6] exit"
todo=$(select_range "choose the action" 1 6)
check_if_succeed $?
case $todo in
"1")
  echo -e "[1] rurima\n[2] rootfstool"
  ROOTFS_TOOL=$(select_range "choose the way to get rootfs" 1 2)
  check_if_succeed $?
  if [[ ${ROOTFS_TOOL} == "[2]" ]]; then
    if [[ $ROOTED == "true" ]]; then
      /data/data/com.termux/files/usr/share/daijin/create_rootfstool.sh -r
    else
      /data/data/com.termux/files/usr/share/daijin/create_rootfstool.sh
    fi
  else
    if [[ $ROOTED == "true" ]]; then
      /data/data/com.termux/files/usr/share/daijin/create_rurima.sh -r
    else
      /data/data/com.termux/files/usr/share/daijin/create_rurima.sh
    fi
  fi
  ;;
"2")
  /data/data/com.termux/files/usr/share/daijin/start.sh
  ;;
"3")
  /data/data/com.termux/files/usr/share/daijin/remove.sh
  ;;
"4")
  if [[ $ROOTED == "true" ]]; then
    /data/data/com.termux/files/usr/share/daijin/register.sh -r
  else
    /data/data/com.termux/files/usr/share/daijin/register.sh
  fi
  ;;
"5")
  /data/data/com.termux/files/usr/share/daijin/clear_rootfs.sh
  ;;
"6") exit ;;
esac
