name: PR Build

on:
  pull_request:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v3.1.0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ruamel.yaml termux-create-package
      - name: Build Package
        run: |
          termux-create-package termux-container.json
          mkdir -p debs
          mv termux-container_1.0_all.deb debs/
          
      - name: Download Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          path: ./debs
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: termux-container_1.0_all.deb
          path: ./debs
      - name: action-shellcheck
        uses: sudo-bot/action-shellcheck@latest
        with:
          cli-args:  -S error container container-zh container-helper
